/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Claudio1' at '09/02/17 14.13' with Gradle 2.14.1
 *
 * @author Claudio1, @date 09/02/17 14.13
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
